### ISSUE TITLE
Request: Differences from Probably.jl

### ISSUE THREAD

**Issue by jakobnissen** [kernelmethod/CuckooFilters.jl#1]
Hey @kernelmethod 

I noticed this repo, which has some overlap with my https://github.com/jakobnissen/Probably.jl. Might be a good idea to include a list of differences from the Cuckoo filters in Probably - or perhaps let the two packages cross-pollinate.

**Comment by kernelmethod** [comment]
Hey! Thanks for reaching out.

Admittedly I was unaware of Probably.jl when I started creating this package. I just took a cursory glance at your cuckoo filter implementation and it's clearly a lot more complete than the one I've started here. When I have a moment I might go ahead and send a couple of PRs your way, but outside of some minor suggestions for e.g. the documentation I don't think there's much I could do to improve what you've already written.

In light of that, it might be best if I went ahead and stopped this package from getting registered into General, at least in its current state. That said, I do think it'd be good for people to have a `CuckooFilters` (or similarly-named) package that exports your `FastCuckoo` / `SmallCuckoo` types to make it easier to search for. What do you think?

**Comment by jakobnissen** [comment]
Yep, makes sense!

I think it's a good idea to stop the registration. At least for now - it's very hard to stop once it's been merged into General, because registered packages are meant to be immutable. I'm ambivalent about making a package in General just to make it easier searchable. One downside of the immutable registry means that once a package name is registered, it can't be deleted. So I'm not comfortable taking a new name just to increase the visibility of the package.

When I search for "julia cuckoo filters", my package comes up as no. 1, but I don't know if that's just because Google has tailored my search results for me. You're right that there is some visibility problems.

There are a few things about Probably.jl I'm unhappy about. Most notably the testing - it's a little harder to test probabilistic data structures than regular data structures, so I never got around to writing a proper test suite with CI and code coverage. But obviously you need good tests. Please go ahead and make PR's, and I'll merge them.

Perhaps the best course of action is to write up the test suite, add some CI, and then publish the package on Julia's Discourse. That should increase visibility without taking another name from the registry. Does that seem OK to you?

**Comment by kernelmethod** [comment]
Okay, I've made a comment on the PR to JuliaRegistries/General (https://github.com/JuliaRegistries/General/pull/30591#issuecomment-784319834), hopefully that should be sufficient to stop it from automerging. In any case the registration window is still open for another 40 hours, which should be plenty of time.

> I'm ambivalent about making a package in General just to make it easier searchable. One downside of the immutable registry means that once a package name is registered, it can't be deleted. So I'm not comfortable taking a new name just to increase the visibility of the package.

Yeah, that's understandable. With the tragedy of the commons that you see with PyPI, crates.io, and similar services, it's definitely difficult to tell whether it's better to reserve a name to improve searchability and stop squatters / people using it maliciously versus letting it sit unreserved for someone else to use.

> Perhaps the best course of action is to write up the test suite, add some CI, and then publish the package on Julia's Discourse. That should increase visibility without taking another name from the registry. Does that seem OK to you?

Sure, that sounds good to me :) I'll see if I can make any improvements to the test suite (I know what you mean about it being harder to test, I had the same experience writing [LSHFunctions.jl](https://github.com/kernelmethod/LSHFunctions.jl) in the past) before you announce it on the community Discourse.

**Comment by kernelmethod** [comment]
Looks like the PR to JuliaRegistries/General has been closed, so I'm closing this issue and archiving the repository.
